# https://github.com/hashicorp/setup-terraform
name: Terraform Validate

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform fmt
      id: fmt
      run: terraform fmt

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform validate
      id: validate
      run: terraform validate -no-color
